plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .idea
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfil.lock
  - gulpfile.js

environment: production
repository: kosatyi/romasheva.design

markdown_ext: markdown,md,liquid

#Others
markdown: kramdown
port: 4004

# Setup
title: Alla Romasheva
summary: UX/UI designer
logo: /assets/favicon/android-icon-192x192.png

url: https://romasheva.design
baseurl: ''

email: alla@romasheva.com
analytics: G-TPL3NET896
languages:
  en: en-US
  uk: uk-UA
  ru: ru-RU

social:
  name: Alla Romasheva (Алла Ромашева)
  profiles:
    facebook: https://www.facebook.com/100024493295482
    twitter: https://twitter.com/AllaRomasheva
    instagram: https://www.instagram.com/romasheva.design/
    linkedin: https://www.linkedin.com/in/romasheva/
    behance: https://www.behance.net/romasheva
    pinterest: https://www.pinterest.com/romasevaalla38/
    dribbble: https://dribbble.com/romasheva
    github: https://github.com/allaromasheva
    pexels: https://www.pexels.com/@alla-romasheva-3820560/


contacts:
  telegram: https://t.me/romasheva
  skype: skype:live:37e58384221057fa?chat
  messenger: https://m.me/romasheva.design

twitter:
  username: allaromasheva

facebook:
  publisher: 100024493295482
  chat: 100930458520274

author:
  name: Alla Romasheva
  url: https://romasheva.design/
  twitter: allaromasheva
  image:
    path: /assets/images/cover.jpg
    height: 512
    width: 512

defaults:

  - scope:
      path: ''
    values:
      lang: 'en'
      layout: 'default'
      alternate:
        en: '/en/'
        ru: '/ru/'
        uk: '/uk/'
      image:
        path: '/assets/images/cover.jpg'
        width: '1000'
        height: '600'
      seo:
        links:
          - https://romasheva.com
          - https://romasheva.cv
          - https://www.facebook.com/romasheva.design/
          - https://www.instagram.com/romasheva.design/
          - https://twitter.com/allaromasheva
          - https://www.linkedin.com/in/romasheva/
          - https://www.behance.net/romasheva
          - https://dribbble.com/romasheva
          - https://ua.linkedin.com/in/romasheva/
          - https://github.com/allaromasheva
          - https://www.pexels.com/@alla-romasheva-3820560/

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:categories/:title.html'

  - scope:
      path: 'en'
    values:
      lang: 'en'
  - scope:
      path: 'ru'
    values:
      lang: 'ru'
  - scope:
      path: 'uk'
    values:
      lang: 'uk'
